### ISSUE TITLE
Revise Circom circuits to include `circuit_path` field

### ISSUE THREAD

**Issue by katiemckeon** [Sindri-Labs/sindri-resources#69]
We no longer require the main circom file of a circom circuit upload to be named `circuit.circom`.  You may now include a field `circuit_path` in your Sindri manifest specifying the full path to your main circom file. 

One way to raise awareness of the new feature is to revise all of our database and tutorial circuits to utilize the feature.  This will probably give the more complicated circuit projects a more informative file structure.

**Comment by KPreisner** [comment]
Done in #77
